package com.sales.visits

import androidx.compose.runtime.staticCompositionLocalOf

/** Tiny in-app localization table. `t["key"]` returns the string for the active language. */
class L(val en: Boolean, private val m: Map<String, String>) {
    operator fun get(k: String): String = m[k] ?: k
}

private val AR_MAP = mapOf(
    "visits" to "الزيارات",
    "report_tab" to "التقرير",
    "insights_tab" to "إحصائيات",
    "settings" to "الإعدادات",
    "profile" to "حسابي",
    "profile_sub" to "بياناتك ومزامنة شغلك",
    "sign_in" to "تسجيل الدخول",
    "create_account" to "إنشاء حساب",
    "account_desc" to "احفظ زياراتك واسترجعها على أي جهاز.",
    "err_bad_login" to "الإيميل أو كلمة السر غير صحيحة.",
    "err_email_exists" to "الإيميل ده مستخدم بالفعل.",
    "err_weak_password" to "كلمة السر قصيرة (6 أحرف على الأقل).",
    "err_provider_disabled" to "لازم تفعّل تسجيل الدخول بالإيميل/كلمة السر في إعدادات Firebase Authentication.",
    "err_bad_key" to "مفتاح Firebase مرفوض — اتأكد إن المفتاح غير مقيَّد بتطبيقات أندرويد فقط.",
    "team_error" to "حصل خطأ، حاول تاني.",
    "full_name" to "الاسم بالكامل",
    "email" to "البريد الإلكتروني",
    "password" to "كلمة المرور",
    "forgot_password" to "نسيت كلمة المرور؟",
    "need_account" to "مستخدم جديد؟ أنشئ حساب",
    "have_account" to "عندي حساب بالفعل",
    "edit_profile" to "تعديل الملف الشخصي",
    "job_title" to "المسمى الوظيفي",
    "job_title_hint" to "مثلاً: مندوب مبيعات",
    "company" to "الشركة",
    "company_hint" to "اسم الشركة",
    "company_email" to "إيميل الشركة",
    "company_email_hint" to "بريد العمل (اختياري)",
    "account_email" to "إيميل الحساب",
    "share_account_email" to "شاركه في بطاقتي",
    "cloud_sync" to "المزامنة السحابية",
    "sync_local" to "محلي فقط",
    "sync_syncing" to "جاري الحفظ…",
    "sync_synced" to "محفوظ",
    "sync_offline" to "بانتظار الإنترنت",
    "sign_out" to "تسجيل الخروج",
    "share_card" to "شارك بطاقتي",
    "share_card_desc" to "خلّي العميل يمسح الكود دا بكاميرته يحفظ بياناتك فورًا.",
    "nfc_hint" to "أو قرّب جهازك من جهاز يدعم NFC للمشاركة باللمس.",
    "firebase_pending" to "ربط Firebase قيد التجهيز",
    "error_name" to "اكتب اسمك.",
    "error_email" to "اكتب بريد إلكتروني صحيح.",
    "error_password" to "كلمة المرور لازم تكون 6 حروف على الأقل.",
    "error_credentials" to "البريد أو كلمة المرور غير صحيحة.",
    "error_email_used" to "البريد ده مسجّل بالفعل.",
    "error_network" to "مفيش اتصال بالإنترنت.",
    "error_too_many" to "محاولات كثيرة. جرّب بعد شوية.",
    "error_auth" to "تعذّر تسجيل الدخول.",
    "reset_sent" to "اتبع الرابط اللي اتبعت على بريدك.",
    "start_first" to "ابدأ بتسجيل أول زيارة",
    "empty_visits_title" to "لسه مفيش زيارات مسجّلة",
    "empty_visits_desc" to "دوس على + تبدأ سجلّك.",
    "report_title" to "تقرير الأسبوع",
    "this_week" to "هذا الأسبوع",
    "last_week" to "الأسبوع الماضي",
    "stat_visits" to "زيارة",
    "stat_clients" to "عميل",
    "stat_success" to "ناجحة",
    "by_type" to "حسب نوع الزيارة",
    "week_details" to "تفاصيل الأسبوع",
    "empty_week" to "مفيش زيارات في الأسبوع ده",
    "copy" to "نسخ",
    "share" to "مشاركة",
    "share_report" to "مشاركة التقرير",
    "insights_sub" to "نظرة عامة على كل الزيارات",
    "total" to "إجمالي",
    "by_outcome" to "حسب النتيجة",
    "visits_by_month" to "الزيارات آخر ٦ شهور",
    "top_clients" to "أكثر العملاء زيارةً",
    "upcoming" to "متابعات قادمة",
    "empty_insights" to "الإحصائيات هتظهر بعد أول زيارة",
    "client_name_hint" to "اسم العميل / الشركة",
    "notes_hint" to "اكتب ملاحظات الزيارة، اللي اتكلمتوا فيه، وأي تفاصيل مهمة...",
    "checklist" to "قائمة مهام",
    "checklist_hint" to "عنصر جديد...",
    "add_image" to "إضافة صورة",
    "customer_info" to "معلومات العميل",
    "more" to "المزيد",
    "delete_visit" to "حذف الزيارة",
    "done" to "تم",
    "contact_person" to "الشخص المسؤول",
    "contact_hint" to "اسم الشخص (اختياري)",
    "industry" to "مجال الشركة",
    "industry_hint" to "مثلاً: تجارة، صناعة، خدمات...",
    "contacts" to "جهات الاتصال",
    "add_contact" to "إضافة جهة اتصال",
    "choose_contact" to "اتصل بمين؟",
    "choose_customer" to "اختر العميل",
    "contact_email_hint" to "الإيميل (اختياري)",
    "location_url" to "رابط الموقع",
    "location_url_hint" to "لينك خرائط جوجل (اختياري)",
    "open_location" to "فتح الموقع",
    "phone" to "رقم التليفون",
    "phone_hint" to "مثلاً: 01xxxxxxxxx",
    "call" to "اتصال",
    "address" to "العنوان",
    "address_hint" to "عنوان العميل (اختياري)",
    "time" to "الوقت",
    "visit_type" to "نوع الزيارة",
    "outcome" to "النتيجة",
    "next_step" to "الخطوة الجاية",
    "next_hint" to "مثلاً: إرسال عرض سعر، متابعة الأسبوع الجاي...",
    "follow_date" to "موعد المتابعة",
    "none" to "بدون",
    "appearance" to "المظهر",
    "theme_auto" to "تلقائي",
    "theme_light" to "فاتح",
    "theme_dark" to "غامق",
    "color_style" to "نمط الألوان",
    "week_start" to "بداية الأسبوع",
    "day_sat" to "السبت", "day_sun" to "الأحد", "day_mon" to "الإثنين", "day_tue" to "الثلاثاء",
    "day_wed" to "الأربعاء", "day_thu" to "الخميس", "day_fri" to "الجمعة",
    "palette_classic" to "كلاسيكي",
    "palette_warm" to "دافئ أخضر",
    "language" to "اللغة",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "lang_auto" to "تلقائي",
    "delete_all" to "حذف كل الزيارات",
    "about" to "عن التطبيق",
    "version" to "الإصدار",
    "delete_all_q" to "حذف كل الزيارات؟",
    "delete_all_desc" to "ده هيمسح كل الزيارات المسجّلة نهائياً.",
    "delete" to "حذف",
    "cancel" to "إلغاء",
    "today" to "اليوم",
    "today_title" to "خط سير النهاردة",
    "today_sub" to "العملاء اللي ناوي تزورهم النهاردة",
    "add_client_hint" to "اسم العميل...",
    "empty_today_title" to "مفيش محطات للنهاردة",
    "empty_today_desc" to "ضيف العملاء اللي هتزورهم وكوّن خط سيرك.",
    "stops_done" to "محطة تمّت",
    "today_progress" to "تقدّم اليوم",
    "day_progress" to "تقدّم اليوم المحدد",
    "empty_day_title" to "مفيش محطات لليوم ده",
    "completed" to "تمّت",
    "remaining" to "متبقية",
    "followups_short" to "متابعة",
    "today_plan" to "خطة الزيارات",
    "quick_result" to "نتيجة سريعة",
    "quick_next" to "الخطوة الجاية",
    "template_quote" to "إرسال عرض سعر",
    "template_call" to "اتصال بالعميل",
    "template_follow" to "تحديد متابعة",
    "open_route" to "افتح خط السير في الخرائط",
    "navigate" to "الاتجاهات",
    "route_limit" to "تم إرسال أول 10 محطات فقط إلى الخرائط",
    "updates" to "التحديثات",
    "check_update" to "التحقق من التحديثات",
    "checking" to "بيتحقق...",
    "up_to_date" to "أحدث إصدار مثبّت",
    "update_available" to "فيه تحديث",
    "downloading" to "بينزّل",
    "install_update" to "تثبيت التحديث",
    "update_failed" to "تعذّر التحقق",
    "customers" to "العملاء",
    "opportunities" to "الفرص",
    "tasks_tab" to "المهام",
    "empty_opps_title" to "مفيش فرص بعد — أضِفها من الموبايل.",
    "empty_tasks_title" to "مفيش مهام.",
    "quotes" to "عروض الأسعار",
    "quote" to "عرض سعر",
    "no_quotes" to "مفيش عروض بعد — أضِفها من الموبايل.",
    "weekly_review" to "المراجعة الأسبوعية",
    "wr_happened" to "اللي تحقق",
    "wr_attention" to "يحتاج انتباه",
    "wr_focus" to "تركيز الأسبوع الجاي",
    "m_won" to "صفقات مكسوبة",
    "m_lost" to "صفقات خاسرة",
    "m_interactions" to "تفاعلات مكتملة",
    "m_quotes_sent" to "عروض مُرسلة",
    "m_new_prospects" to "عملاء محتملون جدد",
    "q_overdue" to "متابعات متأخرة",
    "q_quotes_nofu" to "عروض مُرسلة بلا متابعة",
    "q_opps_nodm" to "فرص بلا صاحب قرار",
    "q_opps_nonext" to "فرص بلا خطوة قادمة",
    "ask_on_track" to "كل حاجة تمام 👍",
    "focus_overdue" to "صفّي المتابعات المتأخرة الأول.",
    "focus_quotes" to "تابع العروض المُرسلة اللي لسه من غير رد.",
    "focus_nextstep" to "حدّد خطوة قادمة بتاريخ لكل فرصة نشطة.",
    "focus_dm" to "حدّد صاحب القرار في الفرص اللي من غير.",
    "focus_ok" to "شغلك متمشّي — حافظ على الإيقاع. 👍",
    "add_customer" to "إضافة عميل",
    "search_customers" to "ابحث بالاسم أو رقم التليفون...",
    "search_visits" to "ابحث في الزيارات والملاحظات...",
    "empty_customers" to "لسه مفيش عملاء",
    "empty_customers_desc" to "أضف أول عميل، أو سجّل زيارة وسيظهر هنا تلقائياً.",
    "no_results" to "مفيش نتائج مطابقة",
    "visit_count" to "زيارة",
    "no_visits" to "لا توجد زيارات بعد",
    "new_customer" to "عميل جديد",
    "customer_details" to "تفاصيل العميل",
    "customer_name" to "اسم العميل / الشركة",
    "customer_notes" to "ملاحظات عن العميل",
    "customer_notes_hint" to "أي تفاصيل ثابتة تساعدك في التعامل مع العميل...",
    "visit_history" to "سجل الزيارات",
    "delete_customer" to "حذف العميل",
    "delete_customer_q" to "حذف العميل؟",
    "delete_customer_desc" to "سيتم حذف بطاقة العميل فقط، وستظل زياراته محفوظة.",
    "reminders" to "التنبيهات",
    "enable_reminders" to "فعّل تنبيهات المتابعة",
    "enable_reminders_desc" to "هنفكّرك في موعد متابعة كل عميل.",
    "due_followups" to "متابعات اليوم والمتأخرة",
    "overdue" to "متأخرة",
    "backup" to "النسخ الاحتياطي",
    "backup_desc" to "احفظ نسخة من العملاء والزيارات على جهازك.",
    "export_backup" to "حفظ نسخة احتياطية",
    "import_backup" to "استعادة نسخة احتياطية",
    "backup_saved" to "تم حفظ النسخة الاحتياطية",
    "backup_restored" to "تمت استعادة البيانات",
    "backup_failed" to "تعذّر قراءة ملف النسخة الاحتياطية",
    "ai_formatting" to "تنسيق الملاحظات بالذكاء الاصطناعي",
    "ai_desc" to "اكتب أو أملِ ملاحظات الزيارة بشكل عادي، والتطبيق ينسّقها احترافيًا بالعربي والإنجليزي. محتاج مفتاح Gemini مجاني.",
    "api_key" to "مفتاح Gemini API",
    "api_key_hint" to "الصق المفتاح هنا",
    "get_key" to "احصل على مفتاح مجاني من Google AI Studio",
    "ai_test" to "اختبار المفتاح",
    "ai_testing" to "جاري الاختبار...",
    "ai_test_ok" to "المفتاح شغّال ✓",
    "ai_saved" to "تم حفظ المفتاح",
    "polish" to "نسّق بالذكاء الاصطناعي",
    "polishing" to "جاري التنسيق...",
    "need_key" to "أضف مفتاح Gemini من الإعدادات الأول",
    "ai_result" to "النسخة المنسّقة",
    "notes_ar_label" to "بالعربي",
    "notes_en_label" to "بالإنجليزي",
    "voice_input" to "تسجيل صوتي",
    "mic_denied" to "محتاج إذن الميكروفون عشان تسجّل",
    "rec_failed" to "التسجيل قصير جدًا أو فشل — جرّب تاني",
    "copied" to "تم النسخ",
    "ai_failed" to "تعذّر التنسيق",
)

private val EN_MAP = mapOf(
    "visits" to "Visits",
    "report_tab" to "Report",
    "insights_tab" to "Insights",
    "settings" to "Settings",
    "profile" to "Profile",
    "profile_sub" to "Your details and cloud sync",
    "sign_in" to "Sign in",
    "create_account" to "Create account",
    "account_desc" to "Keep your visits safe and restore them on any device.",
    "err_bad_login" to "Wrong email or password.",
    "err_email_exists" to "That email is already in use.",
    "err_weak_password" to "Password too short (6+ characters).",
    "err_provider_disabled" to "Enable Email/Password sign-in in Firebase Authentication settings.",
    "err_bad_key" to "Firebase key rejected — make sure it isn't restricted to Android apps only.",
    "team_error" to "Something went wrong, try again.",
    "full_name" to "Full name",
    "email" to "Email",
    "password" to "Password",
    "forgot_password" to "Forgot password?",
    "need_account" to "New here? Create an account",
    "have_account" to "I already have an account",
    "edit_profile" to "Edit profile",
    "job_title" to "Job title",
    "job_title_hint" to "e.g. Sales representative",
    "company" to "Company",
    "company_hint" to "Company name",
    "company_email" to "Company email",
    "company_email_hint" to "Work email (optional)",
    "account_email" to "Account email",
    "share_account_email" to "Share it on my card",
    "cloud_sync" to "Cloud sync",
    "sync_local" to "Local only",
    "sync_syncing" to "Saving…",
    "sync_synced" to "Saved",
    "sync_offline" to "Waiting for internet",
    "sign_out" to "Sign out",
    "share_card" to "Share my card",
    "share_card_desc" to "Let a customer scan this with their camera to save your details instantly.",
    "nfc_hint" to "Or tap your phone to an NFC-enabled device to share.",
    "firebase_pending" to "Firebase connection is being set up",
    "error_name" to "Enter your name.",
    "error_email" to "Enter a valid email.",
    "error_password" to "Password must be at least 6 characters.",
    "error_credentials" to "Incorrect email or password.",
    "error_email_used" to "This email is already registered.",
    "error_network" to "No internet connection.",
    "error_too_many" to "Too many attempts. Try again later.",
    "error_auth" to "Couldn't sign in.",
    "reset_sent" to "Follow the link sent to your email.",
    "start_first" to "Start by logging your first visit",
    "empty_visits_title" to "No visits yet",
    "empty_visits_desc" to "Tap + to start your log.",
    "report_title" to "Weekly report",
    "this_week" to "This week",
    "last_week" to "Last week",
    "stat_visits" to "Visits",
    "stat_clients" to "Clients",
    "stat_success" to "Successful",
    "by_type" to "By visit type",
    "week_details" to "This week's details",
    "empty_week" to "No visits this week",
    "copy" to "Copy",
    "share" to "Share",
    "share_report" to "Share report",
    "insights_sub" to "Overview of all your visits",
    "total" to "Total",
    "by_outcome" to "By outcome",
    "visits_by_month" to "Visits · last 6 months",
    "top_clients" to "Most-visited clients",
    "upcoming" to "Upcoming follow-ups",
    "empty_insights" to "Insights appear after your first visit",
    "client_name_hint" to "Client / company name",
    "notes_hint" to "Write the visit notes, what you discussed, and any important details...",
    "checklist" to "Checklist",
    "checklist_hint" to "New item...",
    "add_image" to "Add image",
    "customer_info" to "Customer info",
    "more" to "More",
    "delete_visit" to "Delete visit",
    "done" to "Done",
    "contact_person" to "Contact person",
    "contact_hint" to "Person's name (optional)",
    "industry" to "Industry",
    "industry_hint" to "e.g. retail, manufacturing, services...",
    "contacts" to "Contacts",
    "add_contact" to "Add contact",
    "choose_contact" to "Who to call?",
    "choose_customer" to "Choose customer",
    "contact_email_hint" to "Email (optional)",
    "location_url" to "Location link",
    "location_url_hint" to "Google Maps link (optional)",
    "open_location" to "Open location",
    "phone" to "Phone number",
    "phone_hint" to "e.g. 01xxxxxxxxx",
    "call" to "Call",
    "address" to "Address",
    "address_hint" to "Client address (optional)",
    "time" to "Time",
    "visit_type" to "Visit type",
    "outcome" to "Outcome",
    "next_step" to "Next step",
    "next_hint" to "e.g. send a quote, follow up next week...",
    "follow_date" to "Follow-up date",
    "none" to "None",
    "appearance" to "Appearance",
    "theme_auto" to "Auto",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "color_style" to "Color style",
    "week_start" to "Week starts on",
    "day_sat" to "Saturday", "day_sun" to "Sunday", "day_mon" to "Monday", "day_tue" to "Tuesday",
    "day_wed" to "Wednesday", "day_thu" to "Thursday", "day_fri" to "Friday",
    "palette_classic" to "Classic",
    "palette_warm" to "Warm green",
    "language" to "Language",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "lang_auto" to "Auto",
    "delete_all" to "Delete all visits",
    "about" to "About",
    "version" to "Version",
    "delete_all_q" to "Delete all visits?",
    "delete_all_desc" to "This permanently deletes all recorded visits.",
    "delete" to "Delete",
    "cancel" to "Cancel",
    "today" to "Today",
    "today_title" to "Today's route",
    "today_sub" to "Clients you plan to visit today",
    "add_client_hint" to "Client name...",
    "empty_today_title" to "No stops for today",
    "empty_today_desc" to "Add the clients you'll visit and build your route.",
    "stops_done" to "stops done",
    "today_progress" to "Today's progress",
    "day_progress" to "Day's progress",
    "empty_day_title" to "No stops for this day",
    "completed" to "Completed",
    "remaining" to "Remaining",
    "followups_short" to "Follow-ups",
    "today_plan" to "Visit plan",
    "quick_result" to "Quick result",
    "quick_next" to "Next step",
    "template_quote" to "Send a quote",
    "template_call" to "Call the customer",
    "template_follow" to "Schedule follow-up",
    "open_route" to "Open route in Maps",
    "navigate" to "Directions",
    "route_limit" to "Only the first 10 stops were sent to Maps",
    "updates" to "Updates",
    "check_update" to "Check for updates",
    "checking" to "Checking...",
    "up_to_date" to "You're on the latest version",
    "update_available" to "Update available",
    "downloading" to "Downloading",
    "install_update" to "Install update",
    "update_failed" to "Couldn't check",
    "customers" to "Customers",
    "opportunities" to "Opportunities",
    "tasks_tab" to "Tasks",
    "empty_opps_title" to "No opportunities yet — add them from mobile.",
    "empty_tasks_title" to "No tasks.",
    "quotes" to "Quotes",
    "quote" to "Quote",
    "no_quotes" to "No quotes yet — add them from mobile.",
    "weekly_review" to "Weekly review",
    "wr_happened" to "What happened",
    "wr_attention" to "Needs attention",
    "wr_focus" to "Focus for next week",
    "m_won" to "Deals won",
    "m_lost" to "Deals lost",
    "m_interactions" to "Completed interactions",
    "m_quotes_sent" to "Quotes sent",
    "m_new_prospects" to "New prospects",
    "q_overdue" to "Overdue follow-ups",
    "q_quotes_nofu" to "Sent quotes without follow-up",
    "q_opps_nodm" to "Deals without a decision maker",
    "q_opps_nonext" to "Deals without a next step",
    "ask_on_track" to "Everything looks on track 👍",
    "focus_overdue" to "Clear overdue follow-ups first.",
    "focus_quotes" to "Follow up on sent quotes with no reply yet.",
    "focus_nextstep" to "Set a dated next step for every active deal.",
    "focus_dm" to "Identify the decision maker on deals that lack one.",
    "focus_ok" to "You're on track — keep the rhythm. 👍",
    "add_customer" to "Add customer",
    "search_customers" to "Search by name or phone...",
    "search_visits" to "Search visits and notes...",
    "empty_customers" to "No customers yet",
    "empty_customers_desc" to "Add your first customer, or log a visit and they will appear automatically.",
    "no_results" to "No matching results",
    "visit_count" to "visits",
    "no_visits" to "No visits yet",
    "new_customer" to "New customer",
    "customer_details" to "Customer details",
    "customer_name" to "Customer / company name",
    "customer_notes" to "Customer notes",
    "customer_notes_hint" to "Any useful long-term details about this customer...",
    "visit_history" to "Visit history",
    "delete_customer" to "Delete customer",
    "delete_customer_q" to "Delete customer?",
    "delete_customer_desc" to "Only the customer card will be removed. Their visits will remain saved.",
    "reminders" to "Reminders",
    "enable_reminders" to "Enable follow-up reminders",
    "enable_reminders_desc" to "We'll remind you when a customer follow-up is due.",
    "due_followups" to "Due and overdue follow-ups",
    "overdue" to "Overdue",
    "backup" to "Backup",
    "backup_desc" to "Keep a copy of your customers and visits on this device.",
    "export_backup" to "Save a backup",
    "import_backup" to "Restore a backup",
    "backup_saved" to "Backup saved",
    "backup_restored" to "Data restored",
    "backup_failed" to "Couldn't read this backup file",
    "ai_formatting" to "AI note formatting",
    "ai_desc" to "Write or dictate your visit notes casually, and the app formats them professionally in Arabic and English. Needs a free Gemini key.",
    "api_key" to "Gemini API key",
    "api_key_hint" to "Paste your key here",
    "get_key" to "Get a free key from Google AI Studio",
    "ai_test" to "Test key",
    "ai_testing" to "Testing...",
    "ai_test_ok" to "Key works ✓",
    "ai_saved" to "Key saved",
    "polish" to "Format with AI",
    "polishing" to "Formatting...",
    "need_key" to "Add a Gemini key in Settings first",
    "ai_result" to "Formatted version",
    "notes_ar_label" to "Arabic",
    "notes_en_label" to "English",
    "voice_input" to "Voice recording",
    "mic_denied" to "Microphone permission is needed to record",
    "rec_failed" to "Recording too short or failed — try again",
    "copied" to "Copied",
    "ai_failed" to "Couldn't format",
)

val AR = L(false, AR_MAP)
val EN = L(true, EN_MAP)

val LocalL = staticCompositionLocalOf { AR }

/** Subtitle: "5 زيارة مسجّلة · 4 هذا الأسبوع" / "5 visits · 4 this week" */
fun visitsSubtitle(total: Int, week: Int, en: Boolean): String =
    if (en) "$total visits · $week this week" else "$total زيارة مسجّلة · $week هذا الأسبوع"
