package com.sales.visits

import androidx.compose.runtime.staticCompositionLocalOf

/** Tiny in-app localization table. `t["key"]` returns the string for the active language. */
class L(val en: Boolean, private val m: Map<String, String>) {
    operator fun get(k: String): String = m[k] ?: k
}

private val AR_MAP = mapOf(
    "visits" to "الزيارات",
    "report_tab" to "التقرير",
    "insights_tab" to "إحصائيات",
    "settings" to "الإعدادات",
    "start_first" to "ابدأ بتسجيل أول زيارة",
    "empty_visits_title" to "لسه مفيش زيارات مسجّلة",
    "empty_visits_desc" to "دوس على + تبدأ سجلّك.",
    "report_title" to "تقرير الأسبوع",
    "this_week" to "هذا الأسبوع",
    "last_week" to "الأسبوع الماضي",
    "stat_visits" to "زيارة",
    "stat_clients" to "عميل",
    "stat_success" to "ناجحة",
    "by_type" to "حسب نوع الزيارة",
    "week_details" to "تفاصيل الأسبوع",
    "empty_week" to "مفيش زيارات في الأسبوع ده",
    "copy" to "نسخ",
    "share" to "مشاركة",
    "share_report" to "مشاركة التقرير",
    "insights_sub" to "نظرة عامة على كل الزيارات",
    "total" to "إجمالي",
    "by_outcome" to "حسب النتيجة",
    "top_clients" to "أكثر العملاء زيارةً",
    "upcoming" to "متابعات قادمة",
    "empty_insights" to "الإحصائيات هتظهر بعد أول زيارة",
    "client_name_hint" to "اسم العميل / الشركة",
    "notes_hint" to "اكتب ملاحظات الزيارة، اللي اتكلمتوا فيه، وأي تفاصيل مهمة...",
    "customer_info" to "معلومات العميل",
    "more" to "المزيد",
    "delete_visit" to "حذف الزيارة",
    "done" to "تم",
    "contact_person" to "الشخص المسؤول",
    "contact_hint" to "اسم الشخص (اختياري)",
    "phone" to "رقم التليفون",
    "phone_hint" to "مثلاً: 01xxxxxxxxx",
    "call" to "اتصال",
    "address" to "العنوان",
    "address_hint" to "عنوان العميل (اختياري)",
    "time" to "الوقت",
    "visit_type" to "نوع الزيارة",
    "outcome" to "النتيجة",
    "next_step" to "الخطوة الجاية",
    "next_hint" to "مثلاً: إرسال عرض سعر، متابعة الأسبوع الجاي...",
    "follow_date" to "موعد المتابعة",
    "none" to "بدون",
    "appearance" to "المظهر",
    "theme_auto" to "تلقائي",
    "theme_light" to "فاتح",
    "theme_dark" to "غامق",
    "language" to "اللغة",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "delete_all" to "حذف كل الزيارات",
    "about" to "عن التطبيق",
    "version" to "الإصدار 1.0",
    "delete_all_q" to "حذف كل الزيارات؟",
    "delete_all_desc" to "ده هيمسح كل الزيارات المسجّلة نهائياً.",
    "delete" to "حذف",
    "cancel" to "إلغاء",
    "today" to "اليوم",
    "today_title" to "خط سير النهاردة",
    "today_sub" to "العملاء اللي ناوي تزورهم النهاردة",
    "add_client_hint" to "اسم العميل...",
    "empty_today_title" to "مفيش محطات للنهاردة",
    "empty_today_desc" to "ضيف العملاء اللي هتزورهم وكوّن خط سيرك.",
    "stops_done" to "محطة تمّت",
    "updates" to "التحديثات",
    "check_update" to "التحقق من التحديثات",
    "checking" to "بيتحقق...",
    "up_to_date" to "أحدث إصدار مثبّت",
    "update_available" to "فيه تحديث",
    "downloading" to "بينزّل",
    "install_update" to "تثبيت التحديث",
    "update_failed" to "تعذّر التحقق",
)

private val EN_MAP = mapOf(
    "visits" to "Visits",
    "report_tab" to "Report",
    "insights_tab" to "Insights",
    "settings" to "Settings",
    "start_first" to "Start by logging your first visit",
    "empty_visits_title" to "No visits yet",
    "empty_visits_desc" to "Tap + to start your log.",
    "report_title" to "Weekly report",
    "this_week" to "This week",
    "last_week" to "Last week",
    "stat_visits" to "Visits",
    "stat_clients" to "Clients",
    "stat_success" to "Successful",
    "by_type" to "By visit type",
    "week_details" to "This week's details",
    "empty_week" to "No visits this week",
    "copy" to "Copy",
    "share" to "Share",
    "share_report" to "Share report",
    "insights_sub" to "Overview of all your visits",
    "total" to "Total",
    "by_outcome" to "By outcome",
    "top_clients" to "Most-visited clients",
    "upcoming" to "Upcoming follow-ups",
    "empty_insights" to "Insights appear after your first visit",
    "client_name_hint" to "Client / company name",
    "notes_hint" to "Write the visit notes, what you discussed, and any important details...",
    "customer_info" to "Customer info",
    "more" to "More",
    "delete_visit" to "Delete visit",
    "done" to "Done",
    "contact_person" to "Contact person",
    "contact_hint" to "Person's name (optional)",
    "phone" to "Phone number",
    "phone_hint" to "e.g. 01xxxxxxxxx",
    "call" to "Call",
    "address" to "Address",
    "address_hint" to "Client address (optional)",
    "time" to "Time",
    "visit_type" to "Visit type",
    "outcome" to "Outcome",
    "next_step" to "Next step",
    "next_hint" to "e.g. send a quote, follow up next week...",
    "follow_date" to "Follow-up date",
    "none" to "None",
    "appearance" to "Appearance",
    "theme_auto" to "Auto",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "language" to "Language",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "delete_all" to "Delete all visits",
    "about" to "About",
    "version" to "Version 1.0",
    "delete_all_q" to "Delete all visits?",
    "delete_all_desc" to "This permanently deletes all recorded visits.",
    "delete" to "Delete",
    "cancel" to "Cancel",
    "today" to "Today",
    "today_title" to "Today's route",
    "today_sub" to "Clients you plan to visit today",
    "add_client_hint" to "Client name...",
    "empty_today_title" to "No stops for today",
    "empty_today_desc" to "Add the clients you'll visit and build your route.",
    "stops_done" to "stops done",
    "updates" to "Updates",
    "check_update" to "Check for updates",
    "checking" to "Checking...",
    "up_to_date" to "You're on the latest version",
    "update_available" to "Update available",
    "downloading" to "Downloading",
    "install_update" to "Install update",
    "update_failed" to "Couldn't check",
)

val AR = L(false, AR_MAP)
val EN = L(true, EN_MAP)

val LocalL = staticCompositionLocalOf { AR }

/** Subtitle: "5 زيارة مسجّلة · 4 هذا الأسبوع" / "5 visits · 4 this week" */
fun visitsSubtitle(total: Int, week: Int, en: Boolean): String =
    if (en) "$total visits · $week this week" else "$total زيارة مسجّلة · $week هذا الأسبوع"
