package com.sales.visits

import androidx.compose.runtime.staticCompositionLocalOf

/** Tiny in-app localization table. `t["key"]` returns the string for the active language. */
class L(val en: Boolean, private val m: Map<String, String>) {
    operator fun get(k: String): String = m[k] ?: k
}

private val AR_MAP = mapOf(
    "visits" to "الزيارات",
    "report_tab" to "التقرير",
    "insights_tab" to "إحصائيات",
    "settings" to "الإعدادات",
    "profile" to "حسابي",
    "profile_sub" to "بياناتك ومزامنة شغلك",
    "sign_in" to "تسجيل الدخول",
    "create_account" to "إنشاء حساب",
    "account_desc" to "احفظ زياراتك واسترجعها على أي جهاز.",
    "full_name" to "الاسم بالكامل",
    "email" to "البريد الإلكتروني",
    "password" to "كلمة المرور",
    "forgot_password" to "نسيت كلمة المرور؟",
    "need_account" to "مستخدم جديد؟ أنشئ حساب",
    "have_account" to "عندي حساب بالفعل",
    "edit_profile" to "تعديل الملف الشخصي",
    "job_title" to "المسمى الوظيفي",
    "job_title_hint" to "مثلاً: مندوب مبيعات",
    "company" to "الشركة",
    "company_hint" to "اسم الشركة",
    "company_email" to "إيميل الشركة",
    "company_email_hint" to "بريد العمل (اختياري)",
    "account_email" to "إيميل الحساب",
    "share_account_email" to "شاركه في بطاقتي",
    "cloud_sync" to "المزامنة السحابية",
    "sync_local" to "محلي فقط",
    "sync_syncing" to "جاري الحفظ…",
    "sync_synced" to "محفوظ",
    "sync_offline" to "بانتظار الإنترنت",
    "sync_outdated" to "حدّث التطبيق للمزامنة",
    "sign_out" to "تسجيل الخروج",
    "share_card" to "شارك بطاقتي",
    "share_card_desc" to "خلّي العميل يمسح الكود دا بكاميرته يحفظ بياناتك فورًا.",
    "nfc_hint" to "أو قرّب جهازك من جهاز يدعم NFC للمشاركة باللمس.",
    "firebase_pending" to "ربط Firebase قيد التجهيز",
    "error_name" to "اكتب اسمك.",
    "error_email" to "اكتب بريد إلكتروني صحيح.",
    "error_password" to "كلمة المرور لازم تكون 6 حروف على الأقل.",
    "error_credentials" to "البريد أو كلمة المرور غير صحيحة.",
    "error_email_used" to "البريد ده مسجّل بالفعل.",
    "error_network" to "مفيش اتصال بالإنترنت.",
    "error_too_many" to "محاولات كثيرة. جرّب بعد شوية.",
    "error_auth" to "تعذّر تسجيل الدخول.",
    "reset_sent" to "اتبع الرابط اللي اتبعت على بريدك.",
    "start_first" to "ابدأ بتسجيل أول زيارة",
    "empty_visits_title" to "لسه مفيش زيارات مسجّلة",
    "empty_visits_desc" to "دوس على + تبدأ سجلّك.",
    "report_title" to "تقرير الأسبوع",
    "this_week" to "هذا الأسبوع",
    "last_week" to "الأسبوع الماضي",
    "stat_visits" to "زيارة",
    "stat_clients" to "عميل",
    "stat_success" to "ناجحة",
    "by_type" to "حسب نوع الزيارة",
    "week_details" to "تفاصيل الأسبوع",
    "empty_week" to "مفيش زيارات في الأسبوع ده",
    "copy" to "نسخ",
    "share" to "مشاركة",
    "share_report" to "مشاركة التقرير",
    "export_excel" to "تصدير Excel",
    "report_lang" to "لغة التقرير",
    "report_lang_desc" to "اللغة اللي يتصدّر بيها التقرير و ملف الإكسل",
    "reminder_time" to "وقت التذكير",
    "daily_goal" to "الهدف اليومي",
    "set_goal_hint" to "حدد هدف زياراتك اليومي",
    "daily_goal_desc" to "عدد الزيارات اللي عايز تعملها في اليوم.",
    "clear_goal" to "إلغاء الهدف",
    "templates" to "قوالب",
    "add_template_hint" to "اكتب قالب جديد...",
    "calendar" to "التقويم",
    "change_photo" to "تغيير الصورة",
    "team" to "الفريق",
    "team_intro" to "أنشئ شركة كمدير، أو انضم لفريق بكود الدعوة.",
    "create_company" to "إنشاء شركة",
    "company_name_hint" to "اسم الشركة",
    "join_company" to "الانضمام بكود",
    "invite_code_hint" to "كود الدعوة",
    "invalid_code" to "كود الدعوة غير صحيح.",
    "team_error" to "حصل خطأ، حاول تاني.",
    "last_manager" to "لازم يفضل مدير واحد على الأقل — رقِّ مديرًا آخر الأول.",
    "role_manager" to "مدير",
    "role_rep" to "مندوب",
    "invite_code" to "كود الدعوة",
    "team_members" to "أعضاء الفريق",
    "team_pipeline" to "خط أنابيب الفريق",
    "team_share_opp" to "شارك فرصة",
    "team_customers" to "عملاء الفريق",
    "team_customers_empty" to "مفيش عملاء متشاركين لسه.",
    "team_customers_hint" to "شارك عميل من صفحة العميل نفسه (زر «شارك مع الفريق»).",
    "share_to_team" to "شارك مع الفريق",
    "share_to_team_desc" to "خلّي كل أعضاء الشركة يشوفوا العميل ده.",
    "shared_with_team" to "متشارك مع الفريق ✓",
    "share" to "شارك",
    "unshare" to "إلغاء المشاركة",
    "team_pipeline_empty" to "مفيش فرص مشتركة بعد.",
    "owner" to "المالك",
    "attachments" to "المرفقات",
    "add_file" to "أضف ملف",
    "no_attachments" to "مفيش مرفقات بعد.",
    "att_local" to "على الجهاز (لسه ما اترفعش)",
    "att_uploaded" to "مرفوع على Drive ✓",
    "drive_sync" to "مزامنة Google (المرفقات + التقويم)",
    "drive_sync_desc" to "اربط حساب Google علشان المرفقات تتزامن بين أجهزتك، والمهام تتحط في تقويمك — مجاناً.",
    "cal_synced" to "اتحطّت في تقويم Google (بتتحدّث لوحدها)",
    "drive_connect" to "اربط",
    "drive_disconnect" to "افصل",
    "drive_connected" to "تم ربط Google Drive",
    "drive_connected_as" to "متصل بـ",
    "you" to "أنت",
    "make_rep" to "اجعله مندوب",
    "make_manager" to "اجعله مدير",
    "leave_company" to "مغادرة الشركة",
    "work_distribution" to "توزيع العمل",
    "assign_work" to "إسناد مهمة",
    "no_assignments" to "لا توجد مهام مُسندة بعد.",
    "assign_to" to "الإسناد إلى",
    "note" to "ملاحظة",
    "opportunities" to "فرص البيع",
    "empty_opps_title" to "مفيش فرص بعد",
    "empty_opps_desc" to "ضيف فرص البيع وتابع مراحلها.",
    "opps_total" to "الفرص",
    "open_value" to "قيمة مفتوحة",
    "stage_won" to "تم البيع",
    "stage_lost" to "لم تتم",
    "stage_postponed" to "مؤجلة",
    "opp_active" to "نشطة",
    "opp_view_toggle" to "عرض لوحة / قائمة",
    "new_opp" to "فرصة جديدة",
    "edit_opp" to "تعديل الفرصة",
    "opp_title" to "عنوان الفرصة",
    "opp_title_hint" to "مثال: صفقة طابعات لشركة كذا",
    "opp_value" to "القيمة",
    "opp_product" to "المنتج / الحل المقترح",
    "opp_product_hint" to "إيه اللي هنعرضه للعميل",
    "opp_need" to "احتياج العميل",
    "opp_need_hint" to "العميل محتاج إيه بالظبط",
    "opp_problem" to "المشكلة وتأثيرها",
    "opp_problem_hint" to "المشكلة اللي بيواجهها وتأثيرها عليه",
    "opp_budget" to "الميزانية",
    "opp_budget_amount" to "قيمة الميزانية",
    "opp_close_date" to "توقيت الشراء المتوقع",
    "opp_competitor" to "المنافس",
    "opp_competitor_hint" to "مين المنافس لو معروف",
    "opp_blocker" to "العائق الحالي",
    "opp_blocker_hint" to "إيه اللي واقف قدام الصفقة",
    "opp_decision_people" to "أصحاب القرار في الصفقة",
    "decision_maker" to "صاحب قرار",
    "opp_missing_prefix" to "قبل عرض السعر لسه ناقص:",
    "opp_needs_next" to "فرصة نشطة من غير خطوة قادمة بتاريخ.",
    "opp_loss_reason" to "سبب الخسارة",
    "opp_loss_reason_hint" to "ليه الصفقة اتخسرت",
    "loss_declared" to "العميل صرّح به",
    "loss_inferred" to "استنتاج مني",
    "opp_history" to "سجل المراحل",
    "quotes" to "عروض الأسعار",
    "quote" to "عرض سعر",
    "new_quote" to "عرض جديد",
    "no_quotes" to "لا توجد عروض بعد",
    "quote_status" to "الحالة",
    "quote_tax" to "الضريبة %",
    "quote_expiry" to "تاريخ الانتهاء",
    "quote_lines" to "البنود",
    "quote_line_desc" to "الوصف / المنتج",
    "quote_qty" to "الكمية",
    "quote_unit_price" to "سعر الوحدة",
    "quote_discount" to "خصم %",
    "quote_unit_cost" to "التكلفة",
    "quote_cost" to "إجمالي التكلفة",
    "quote_profit" to "الربح",
    "quote_export_pdf" to "تصدير PDF",
    "quote_pdf_failed" to "تعذّر إنشاء الملف",
    "quote_line_net" to "الصافي",
    "quote_add_line" to "+ بند",
    "quote_add_stock" to "+ من المخزون",
    "quote_subtotal" to "الإجمالي الفرعي",
    "quote_total" to "الإجمالي",
    "quote_revision_note" to "تعديل بنود عرض مُرسل بيحفظ نسخة جديدة (revision) والأصلي بيفضل زي ما استلمه العميل.",
    "quote_order_created" to "تم إنشاء طلب من هذا العرض ✓",
    "quote_make_order" to "إنشاء طلب من العرض",
    "quote_pick_product" to "اختر منتجًا",
    "dashboard" to "لوحة المدير",
    "team_goal" to "هدف الفريق",
    "team_goal_desc" to "عدد المهام المطلوب إنجازها من الفريق.",
    "set_goal" to "حدّد الهدف",
    "assigned_total" to "مُسندة",
    "by_rep" to "حسب المندوب",
    "note_ar" to "العربية",
    "note_en" to "الإنجليزية",
    "tasks_added_prefix" to "المساعد ضاف مهام:",
    "tools" to "الأدوات",
    "inventory" to "المخزون",
    "prices" to "الأسعار",
    "ai_send" to "إرسال للمساعد",
    "select" to "تحديد",
    "select_all" to "تحديد الكل",
    "search_items" to "ابحث عن صنف...",
    "import_excel" to "استيراد Excel",
    "import_hint" to "ملف Excel/CSV بأعمدة: الاسم، الكمية، السعر، العملة.",
    "imported_prefix" to "تم استيراد أصناف:",
    "import_empty" to "مفيش أصناف في الملف.",
    "import_failed" to "تعذّر قراءة الملف. اتأكد إنه Excel أو CSV.",
    "edit" to "تعديل",
    "orders" to "الأوردرات",
    "purchases" to "المشتريات",
    "total_purchased" to "إجمالي المشتريات",
    "add_order" to "إضافة أوردر",
    "no_orders" to "مفيش أوردرات لسه.",
    "order" to "أوردر",
    "order_ordered" to "تحت التنفيذ",
    "order_delivered" to "تم التسليم",
    "new_order" to "أوردر جديد",
    "edit_order" to "تعديل الأوردر",
    "order_items" to "الأصناف / الوصف",
    "order_items_hint" to "مثال: 3 طابعات أتيكس 1500",
    "order_amount" to "المبلغ",
    "order_status" to "الحالة",
    "order_date" to "التاريخ",
    "mail" to "البريد",
    "mail_desc" to "جهّز إيميل واختار المستلم من جهات اتصال العملاء، وابعته من تطبيق الإيميل.",
    "mail_to" to "إلى",
    "mail_to_hint" to "بريد المستلم",
    "mail_subject" to "الموضوع",
    "mail_subject_hint" to "موضوع الرسالة",
    "mail_body" to "الرسالة",
    "mail_body_hint" to "اكتب رسالتك...",
    "mail_send" to "إرسال",
    "mail_pick" to "اختيار من العملاء",
    "no_mail_app" to "مفيش تطبيق إيميل على الجهاز.",
    "mail_hint_note" to "هيفتح تطبيق الإيميل بالرسالة جاهزة — تراجعها وتبعتها بنفسك.",
    "no_contact_emails" to "مفيش إيميلات محفوظة في جهات اتصال العملاء.",
    "inventory_desc" to "المخزون والأسعار اللي المساعد بيراجعها علشان يقترح الخطوة التالية.",
    "stock_prices" to "المخزون والأسعار",
    "empty_inventory_title" to "مفيش أصناف بعد",
    "empty_inventory_desc" to "ضيف أصنافك بالكميات والأسعار.",
    "no_price" to "السعر غير محدد",
    "in_stock" to "متوفر",
    "out_of_stock" to "غير متوفر",
    "new_item" to "صنف جديد",
    "edit_item" to "تعديل الصنف",
    "item_name" to "اسم الصنف",
    "item_name_hint" to "مثال: طابعة أتيكس 1500",
    "quantity" to "الكمية",
    "price" to "السعر",
    "currency" to "العملة",
    "currency_hint" to "مثال: SAR",
    "default_currency" to "العملة الافتراضية",
    "default_currency_desc" to "العملة اللي تظهر مع الأسعار والقيم.",
    "custom_currency" to "عملة أخرى",
    "insights_sub" to "نظرة عامة على كل الزيارات",
    "total" to "إجمالي",
    "by_outcome" to "حسب النتيجة",
    "visits_by_month" to "الزيارات آخر ٦ شهور",
    "top_clients" to "أكثر العملاء زيارةً",
    "upcoming" to "متابعات قادمة",
    "empty_insights" to "الإحصائيات هتظهر بعد أول زيارة",
    "client_name_hint" to "اسم العميل / الشركة",
    "notes_hint" to "اكتب ملاحظات الزيارة، اللي اتكلمتوا فيه، وأي تفاصيل مهمة...",
    "checklist" to "قائمة مهام",
    "checklist_hint" to "عنصر جديد...",
    "add_image" to "إضافة صورة",
    "customer_info" to "معلومات العميل",
    "more" to "المزيد",
    "delete_visit" to "حذف الزيارة",
    "done" to "تم",
    "contact_person" to "الشخص المسؤول",
    "contact_hint" to "اسم الشخص (اختياري)",
    "industry" to "مجال الشركة",
    "industry_hint" to "مثلاً: تجارة، صناعة، خدمات...",
    "all" to "الكل",
    "relationship" to "نوع العلاقة",
    "city" to "المدينة",
    "city_hint" to "مثلاً: الرياض",
    "region" to "المنطقة",
    "region_hint" to "مثلاً: المنطقة الوسطى",
    "website" to "الموقع الإلكتروني",
    "website_hint" to "www...",
    "source" to "مصدر التعارف",
    "source_hint" to "مثلاً: ترشيح، معرض، اتصال، الموقع...",
    "equipment" to "المعدات الحالية",
    "equipment_hint" to "الماكينات/المعدات اللي عندهم دلوقتي",
    "apps_field" to "التطبيقات/الأعمال",
    "apps_hint" to "نوع الشغل أو التطبيقات اللي بيشتغلوا عليها",
    "job_title_hint" to "المسمى الوظيفي (مثلاً: مدير إنتاج)",
    "decision_role" to "الدور في القرار",
    "contacts" to "جهات الاتصال",
    "add_contact" to "إضافة جهة اتصال",
    "choose_contact" to "اتصل بمين؟",
    "choose_customer" to "اختر العميل",
    "contact_email_hint" to "الإيميل (اختياري)",
    "location_url" to "رابط الموقع",
    "location_url_hint" to "لينك خرائط جوجل (اختياري)",
    "open_location" to "فتح الموقع",
    "phone" to "رقم التليفون",
    "phone_hint" to "مثلاً: 01xxxxxxxxx",
    "call" to "اتصال",
    "address" to "العنوان",
    "address_hint" to "عنوان العميل (اختياري)",
    "time" to "الوقت",
    "visit_type" to "نوع الزيارة",
    "outcome" to "النتيجة",
    "next_step" to "الخطوة الجاية",
    "next_hint" to "مثلاً: إرسال عرض سعر، متابعة الأسبوع الجاي...",
    "follow_date" to "موعد المتابعة",
    "none" to "بدون",
    "appearance" to "المظهر",
    "set_appearance" to "المظهر",
    "set_preferences" to "التفضيلات",
    "set_account" to "الحساب والمزامنة",
    "set_ai" to "المساعد الذكي",
    "set_data" to "البيانات والنسخ الاحتياطي",
    "set_updates" to "التحديثات والمعلومات",
    "tools_sec_pipeline" to "الفرص والمبيعات",
    "tools_sec_insights" to "التحليلات والتقارير",
    "tools_sec_catalog" to "المنتجات والكتالوج",
    "tools_sec_team" to "الفريق والتواصل",
    "theme_auto" to "تلقائي",
    "theme_light" to "فاتح",
    "theme_dark" to "غامق",
    "color_style" to "نمط الألوان",
    "week_start" to "بداية الأسبوع",
    "day_sat" to "السبت", "day_sun" to "الأحد", "day_mon" to "الإثنين", "day_tue" to "الثلاثاء",
    "day_wed" to "الأربعاء", "day_thu" to "الخميس", "day_fri" to "الجمعة",
    "palette_classic" to "كلاسيكي",
    "palette_warm" to "دافئ أخضر",
    "language" to "اللغة",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "lang_auto" to "تلقائي",
    "delete_all" to "حذف كل الزيارات",
    "about" to "عن التطبيق",
    "version" to "الإصدار",
    "delete_all_q" to "حذف كل الزيارات؟",
    "delete_all_desc" to "ده هيمسح كل الزيارات المسجّلة نهائياً.",
    "delete" to "حذف",
    "cancel" to "إلغاء",
    "client_required" to "اكتب اسم العميل الأول.",
    "discard" to "تجاهل",
    "keep_editing" to "أكمّل التعديل",
    "discard_q" to "تخرج من غير حفظ؟",
    "discard_desc" to "لسه ناقص نتيجة الزيارة أو الخطوة التالية. لو خرجت دلوقتي البيانات مش هتتحفظ.",
    "discard_no_client" to "ناقص اسم العميل. لو خرجت دلوقتي البيانات مش هتتحفظ.",
    "today" to "اليوم",
    "today_title" to "خط سير النهاردة",
    "today_sub" to "العملاء اللي ناوي تزورهم النهاردة",
    "add_client_hint" to "اسم العميل...",
    "plan_hint" to "اكتب المهمة، و@ لاختيار العميل",
    "add" to "إضافة",
    "seg_all" to "الكل",
    "seg_todo" to "المتبقّي",
    "seg_done" to "المكتملة",
    "seg_none_todo" to "مفيش محطات متبقّية 🎉",
    "seg_none_done" to "لسه مفيش محطة اتخلصت",
    "tasks_tab" to "المهام",
    "save" to "حفظ",
    "of" to "من",
    "hrs" to "س",
    "duration" to "المدة",
    "morning" to "الصباح",
    "afternoon" to "الظهر",
    "evening" to "المساء",
    "new_task" to "مهمة جديدة",
    "edit_task" to "تعديل المهمة",
    "task_action" to "المهمة",
    "task_status" to "الحالة",
    "task_details" to "تفاصيل المهمة",
    "task_source" to "المصدر",
    "date" to "التاريخ",
    "result" to "النتيجة",
    "mark_done" to "علّمها تمّت",
    "mark_undone" to "رجّعها مفتوحة",
    "add_to_calendar" to "أضف للتقويم",
    "empty_tasks_title" to "مفيش مهام للنهاردة",
    "empty_tasks_desc" to "ضيف مهامك واتابع تقدّمك.",
    "reschedule" to "نقل ليوم تاني",
    "move_tomorrow" to "انقل لبكرة",
    "move_day_after" to "انقل لبعد بكرة",
    "move_pick_day" to "اختار يوم",
    "empty_today_title" to "مفيش محطات للنهاردة",
    "empty_today_desc" to "ضيف العملاء اللي هتزورهم وكوّن خط سيرك.",
    "stops_done" to "محطة تمّت",
    "today_progress" to "تقدّم اليوم",
    "day_progress" to "تقدّم اليوم المحدد",
    "empty_day_title" to "مفيش محطات لليوم ده",
    "completed" to "تمّت",
    "remaining" to "متبقية",
    "followups_short" to "متابعة",
    "today_plan" to "خطة الزيارات",
    "quick_result" to "نتيجة سريعة",
    "quick_next" to "الخطوة الجاية",
    "template_quote" to "إرسال عرض سعر",
    "template_call" to "اتصال بالعميل",
    "template_follow" to "تحديد متابعة",
    "open_route" to "افتح خط السير في الخرائط",
    "navigate" to "الاتجاهات",
    "route_limit" to "تم إرسال أول 10 محطات فقط إلى الخرائط",
    "updates" to "التحديثات",
    "check_update" to "التحقق من التحديثات",
    "checking" to "بيتحقق...",
    "up_to_date" to "أحدث إصدار مثبّت",
    "update_available" to "فيه تحديث",
    "downloading" to "بينزّل",
    "install_update" to "تثبيت التحديث",
    "update_failed" to "تعذّر التحقق",
    "customers" to "العملاء",
    "add_customer" to "إضافة عميل",
    "search_customers" to "ابحث بالاسم أو رقم التليفون...",
    "search_visits" to "ابحث في الزيارات والملاحظات...",
    "empty_customers" to "لسه مفيش عملاء",
    "empty_customers_desc" to "أضف أول عميل، أو سجّل زيارة وسيظهر هنا تلقائياً.",
    "no_results" to "مفيش نتائج مطابقة",
    "visit_count" to "زيارة",
    "no_visits" to "لا توجد زيارات بعد",
    "new_customer" to "عميل جديد",
    "customer_details" to "تفاصيل العميل",
    "customer_name" to "اسم العميل / الشركة",
    "customer_notes" to "ملاحظات عن العميل",
    "customer_notes_hint" to "أي تفاصيل ثابتة تساعدك في التعامل مع العميل...",
    "visit_history" to "سجل الزيارات",
    "timeline" to "السجل الزمني",
    "visit" to "زيارة",
    "log_activity" to "تسجيل نشاط",
    "edit_activity" to "تعديل النشاط",
    "no_activity" to "لا يوجد نشاط بعد",
    "activity_type" to "نوع النشاط",
    "activity_result" to "النتيجة",
    "activity_date" to "التاريخ",
    "activity_summary" to "ملخص",
    "activity_summary_hint" to "اكتب اللي حصل في المكالمة/الاجتماع...",
    "opp_link" to "اربط بفرصة",
    "delete_customer" to "حذف العميل",
    "delete_customer_q" to "حذف العميل؟",
    "delete_customer_desc" to "سيتم حذف بطاقة العميل فقط، وستظل زياراته محفوظة.",
    "reminders" to "التنبيهات",
    "enable_reminders" to "فعّل تنبيهات المتابعة",
    "enable_reminders_desc" to "هنفكّرك في موعد متابعة كل عميل.",
    "due_followups" to "متابعات اليوم والمتأخرة",
    "agenda_overdue" to "متأخر",
    "agenda_today" to "المطلوب اليوم",
    "agenda_suggestions" to "يحتاج قرار",
    "reason_appointment" to "موعد",
    "reason_due_today" to "اليوم",
    "reason_needs_action" to "فرصة بلا خطوة",
    "reason_expired" to "عرض منتهي",
    "postpone" to "تأجيل",
    "smart_automation" to "الأتمتة الذكية",
    "smart_automation_desc" to "عرض مُرسل → متابعة تلقائية وتقديم مرحلة الصفقة؛ وإغلاق الصفقة → إلغاء متابعاتها القادمة.",
    "agree" to "موافق",
    "retry" to "إعادة المحاولة",
    "previsit_prep" to "جهّزني للزيارة",
    "previsit_pick_opp" to "اختر الفرصة",
    "previsit_general" to "ملخص عام (كل الفرص)",
    "previsit_thinking" to "بجهّز الملخص من بياناتك...",
    "previsit_summary" to "الملخص",
    "previsit_goal" to "هدف مقترح للزيارة",
    "previsit_questions" to "أسئلة مهمة تسألها",
    "previsit_commitments" to "وعود/التزامات سابقة",
    "previsit_watch" to "أمور تحتاج تحقّق",
    "previsit_disclaimer" to "مبني على المسجّل في التطبيق فقط؛ راجعه قبل الاعتماد عليه.",
    "ai_consent_title" to "استخدام المساعد الذكي",
    "ai_consent_desc" to "هيتبعت جزء من بيانات العميل المختار (الملخص، آخر التفاعلات، الفرص، العروض) لمزوّد الـAI (Gemini) بمفتاحك عشان يجهّز الملخص. مفيش مفاتيح بتتبعت، والميزة بتتقفل من الإعدادات.",
    "compose_ai" to "اكتب رسالة (AI)",
    "compose_type" to "نوع الرسالة",
    "compose_tone" to "النبرة",
    "compose_recipient" to "المستلم",
    "compose_generate" to "توليد المسودة",
    "compose_regenerate" to "إعادة التوليد",
    "compose_subject" to "العنوان",
    "compose_body" to "النص",
    "extract_details" to "استخرج التفاصيل (AI)",
    "extract_need_note" to "اكتب أو سجّل ملاحظة الأول.",
    "extract_title" to "تفاصيل مستخرجة من الزيارة",
    "extract_apply_to" to "هتتطبّق على",
    "extract_new_deal" to "مفيش فرصة — هيتعمل فرصة جديدة للعميل ده.",
    "extract_nothing" to "مفيش تفاصيل واضحة تُستخرج.",
    "extract_objection" to "اعتراض",
    "extract_suggestion_note" to "دي اقتراحات محتاجة تأكيدك — شيل علامة أي حاجة مش عايز تطبّقها.",
    "extract_current" to "الحالي",
    "extract_proposed" to "المقترح",
    "extract_apply" to "تطبيق المحدد",
    "assistant" to "المساعد",
    "assistant_hint" to "اكتب أمر بلغتك — أنا بحوّله لإجراء وتأكّده قبل ما يتنفّذ.",
    "assistant_placeholder" to "مثال: ضيف متابعة لأحمد الخميس ١٠ص",
    "cmd_add_task" to "إضافة متابعة",
    "cmd_customer_unmatched" to "العميل ده مش لاقيه بالظبط — هيتضاف بالاسم زي ما هو.",
    "cmd_confirm" to "تأكيد",
    "cmd_dup" to "فيه متابعة زيّها موجودة بالفعل.",
    "cmd_added" to "تمت الإضافة ✓",
    "cmd_reschedule" to "نقل متابعة",
    "cmd_task_not_found" to "ملقتش متابعة مطابقة.",
    "cmd_moved" to "تم النقل ✓",
    "cmd_unknown" to "مفهمتش الأمر — جرّب صياغة تانية.",
    "ask_data" to "اسأل بياناتك",
    "ask_coach" to "مدرّب المبيعات",
    "ask_on_track" to "كل حاجة تمام حاليًا 👍",
    "ask_summarize" to "لخّص بالـAI",
    "ask_scope_note" to "كل الأرقام محسوبة محليًا من بياناتك (المتأخر محسوب حتى اليوم).",
    "q_overdue" to "متابعات متأخرة",
    "q_quotes_nofu" to "عروض مُرسلة بلا متابعة مسجّلة",
    "q_opps_nodm" to "فرص نشطة بلا صاحب قرار",
    "q_opps_nonext" to "فرص نشطة بلا خطوة قادمة",
    "q_prospects" to "عملاء محتملون",
    "analytics" to "التحليلات",
    "period_week" to "الأسبوع",
    "period_month" to "الشهر",
    "period_30" to "آخر ٣٠ يوم",
    "m_new_prospects" to "عملاء محتملون جدد",
    "m_interactions" to "تفاعلات مكتملة",
    "m_no_answer" to "مكالمات بلا رد",
    "m_quotes_sent" to "عروض مُرسلة",
    "m_won" to "صفقات مكسوبة",
    "m_lost" to "صفقات خاسرة",
    "m_adherence" to "الالتزام بالمتابعة",
    "m_pipeline" to "قيمة الفرص النشطة (Pipeline)",
    "m_pipeline_note" to "لقطة حالية، مش محصورة بالفترة.",
    "m_won_value" to "قيمة المكسوب في الفترة",
    "m_sales" to "مبيعات فعلية (طلبات) في الفترة",
    "m_sales_note" to "الطلبات الفعلية — منفصلة عن الـPipeline.",
    "analytics_note" to "كل الأرقام محسوبة محليًا. المقارنة مع فترة سابقة بنفس الطول. العملات مفصولة ومش بتتجمع.",
    "weekly_review" to "المراجعة الأسبوعية",
    "generated" to "أُنشئ",
    "wr_happened" to "اللي تحقق",
    "wr_attention" to "يحتاج انتباه",
    "wr_focus" to "تركيز الأسبوع الجاي",
    "wr_add_focus" to "أضفه كمهمة اليوم",
    "wr_ai_summary" to "ملخص بالـAI (اختياري)",
    "wr_fact_note" to "الأرقام حقائق محسوبة محليًا؛ ملخص الـAI اقتراح للقراءة مش مصدر أرقام.",
    "focus_overdue" to "صفّي المتابعات المتأخرة الأول — دي أكتر حاجة بتعطّل الصفقات.",
    "focus_quotes" to "تابع العروض المُرسلة اللي لسه من غير رد مسجّل.",
    "focus_nextstep" to "حدّد خطوة قادمة بتاريخ لكل فرصة نشطة.",
    "focus_dm" to "حدّد صاحب القرار في الفرص اللي لسه من غير.",
    "focus_ok" to "شغلك متمشّي — حافظ على الإيقاع. 👍",
    "dev_goal" to "هدف تطوير الأسبوع",
    "dev_last_goal" to "هدف الأسبوع اللي فات",
    "dev_goal_hint" to "سلوك واحد تشتغل عليه (مثال: أوثّق صاحب القرار في كل فرصة)",
    "dev_save_goal" to "احفظ الهدف",
    "dev_goal_note" to "سلوك قابل للقياس، بيتراجع الأسبوع الجاي — مفيش درجة من 100.",
    "lost_deals" to "الصفقات الخاسرة",
    "lost_patterns" to "أنماط متكررة",
    "lost_pattern_note" to "بيظهر النمط لما يتكرر (مرتين أو أكتر) — مش من حالة واحدة.",
    "lost_none" to "مفيش صفقات خاسرة مسجّلة.",
    "lost_last_stage" to "آخر مرحلة",
    "lost_duration" to "مدة الصفقة",
    "lost_reason" to "سبب الخسارة",
    "days" to "يوم",
    "lost_reflect" to "أسئلة للمراجعة",
    "lost_q1" to "إيه أول علامة خطر ظهرت؟",
    "lost_q2" to "إيه اللي كنا نعرفه وما تصرّفناش بيه؟",
    "lost_q3" to "إيه السلوك اللي نجرّب نغيّره المرة الجاية؟",
    "product_knowledge" to "المنتجات والمعرفة",
    "objections" to "مكتبة الاعتراضات",
    "projects" to "المشاريع وخريطة الحساب",
    "proj_none" to "مفيش مشاريع لسه. ضيف مشروع كبير وجمّع صفقاته.",
    "proj_deals" to "صفقة",
    "proj_stakeholders" to "صاحب قرار",
    "proj_add" to "مشروع جديد",
    "proj_edit" to "تعديل المشروع",
    "proj_name" to "اسم المشروع",
    "proj_desc" to "الوصف",
    "proj_status" to "الحالة",
    "proj_target" to "تاريخ القرار المتوقع",
    "proj_link_deals" to "الصفقات المرتبطة",
    "proj_no_deals" to "مفيش فرص لهذا العميل — ضيف فرصة أولاً علشان تربطها.",
    "proj_total" to "إجمالي قيمة المشروع",
    "account_map" to "خريطة الحساب (أصحاب القرار)",
    "needs_linking" to "يحتاج ربط",
    "needs_linking_desc" to "سجلات باسم عميل مش مربوط برقم عميل ثابت — اختار العميل الصح علشان تربطها كلها.",
    "needs_linking_none" to "كل السجلات مربوطة ✓",
    "needs_linking_records" to "سجل",
    "needs_linking_link" to "اربط",
    "pk_search" to "ابحث بالاحتياج (مثال: طباعة على قماش)",
    "pk_no_match" to "مفيش منتج مطابق للاحتياج ده.",
    "pk_match_why" to "طابق في",
    "pk_none" to "مفيش منتجات معرفة بعد. ضيف واحد بزرار +",
    "pk_verified" to "موثّق",
    "pk_needs_check" to "يحتاج تحقّق",
    "pk_add" to "منتج جديد",
    "pk_edit" to "تعديل المنتج",
    "pk_name" to "اسم المنتج",
    "pk_manufacturer" to "المصنّع",
    "pk_model" to "الموديل",
    "pk_specs" to "المواصفات",
    "pk_applications" to "الاستخدامات/التطبيقات",
    "pk_materials" to "الخامات المدعومة",
    "pk_limits" to "القيود",
    "pk_suitable" to "مناسب لـ",
    "pk_source" to "المصدر",
    "pk_verified_toggle" to "المعلومة موثّقة",
    "obj_none" to "مفيش اعتراضات مسجّلة. ضيف واحد بزرار +",
    "obj_add" to "اعتراض جديد",
    "obj_edit" to "تعديل الاعتراض",
    "obj_text" to "الاعتراض",
    "obj_probe" to "سؤال استكشاف",
    "obj_evidence" to "دليل/حالة استخدام",
    "obj_response" to "الرد المقترح",
    "overdue" to "متأخرة",
    "backup" to "النسخ الاحتياطي",
    "backup_desc" to "احفظ نسخة من العملاء والزيارات على جهازك.",
    "export_backup" to "حفظ نسخة احتياطية",
    "import_backup" to "استعادة نسخة احتياطية",
    "backup_saved" to "تم حفظ النسخة الاحتياطية",
    "backup_restored" to "تمت استعادة البيانات",
    "backup_failed" to "تعذّر قراءة ملف النسخة الاحتياطية",
    "ai_formatting" to "تنسيق الملاحظات بالذكاء الاصطناعي",
    "ai_desc" to "اكتب أو أملِ ملاحظات الزيارة بشكل عادي، والتطبيق ينسّقها احترافيًا بالعربي والإنجليزي. محتاج مفتاح Gemini مجاني.",
    "api_key" to "مفتاح Gemini API",
    "api_key_hint" to "الصق المفتاح هنا",
    "get_key" to "احصل على مفتاح مجاني من Google AI Studio",
    "ai_test" to "اختبار المفتاح",
    "ai_testing" to "جاري الاختبار...",
    "ai_test_ok" to "المفتاح شغّال ✓",
    "ai_saved" to "تم حفظ المفتاح",
    "polish" to "نسّق بالذكاء الاصطناعي",
    "polishing" to "جاري التنسيق...",
    "purpose" to "سبب الزيارة",
    "purpose_desc" to "اختر سبب الزيارة (إجباري).",
    "need_key" to "أضف مفتاح Gemini من الإعدادات الأول",
    "ai_result" to "النسخة المنسّقة",
    "notes_ar_label" to "بالعربي",
    "notes_en_label" to "بالإنجليزي",
    "voice_input" to "تسجيل صوتي",
    "mic_denied" to "محتاج إذن الميكروفون عشان تسجّل",
    "rec_failed" to "التسجيل قصير جدًا أو فشل — جرّب تاني",
    "copied" to "تم النسخ",
    "ai_failed" to "تعذّر التنسيق",
    "voice_assistant" to "المساعد الصوتي",
    "voice_assistant_desc" to "اتكلم واسأل عن يومك وبياناتك.",
    "voice_you_said" to "قلت:",
    "voice_listening" to "بسمعك…",
    "voice_thinking" to "بفكّر…",
    "voice_speaking" to "برد…",
    "voice_tap_to_talk" to "دوس واتكلم",
    "voice_replay" to "إعادة",
    "voice_examples" to "مثال: «عندي كام زيارة النهاردة؟» · «مين المتأخر في المتابعات؟»",
    "voice_didnt_catch" to "معرفتش أسمعك، جرّب تاني.",
    "voice_unavailable" to "التعرّف على الصوت مش متاح على الجهاز ده.",
    "voice_need_mic" to "محتاج إذن الميكروفون علشان أسمعك.",
)

private val EN_MAP = mapOf(
    "visits" to "Visits",
    "report_tab" to "Report",
    "insights_tab" to "Insights",
    "settings" to "Settings",
    "profile" to "Profile",
    "profile_sub" to "Your details and cloud sync",
    "sign_in" to "Sign in",
    "create_account" to "Create account",
    "account_desc" to "Keep your visits safe and restore them on any device.",
    "full_name" to "Full name",
    "email" to "Email",
    "password" to "Password",
    "forgot_password" to "Forgot password?",
    "need_account" to "New here? Create an account",
    "have_account" to "I already have an account",
    "edit_profile" to "Edit profile",
    "job_title" to "Job title",
    "job_title_hint" to "e.g. Sales representative",
    "company" to "Company",
    "company_hint" to "Company name",
    "company_email" to "Company email",
    "company_email_hint" to "Work email (optional)",
    "account_email" to "Account email",
    "share_account_email" to "Share it on my card",
    "cloud_sync" to "Cloud sync",
    "sync_local" to "Local only",
    "sync_syncing" to "Saving…",
    "sync_synced" to "Saved",
    "sync_offline" to "Waiting for internet",
    "sync_outdated" to "Update the app to sync",
    "sign_out" to "Sign out",
    "share_card" to "Share my card",
    "share_card_desc" to "Let a customer scan this with their camera to save your details instantly.",
    "nfc_hint" to "Or tap your phone to an NFC-enabled device to share.",
    "firebase_pending" to "Firebase connection is being set up",
    "error_name" to "Enter your name.",
    "error_email" to "Enter a valid email.",
    "error_password" to "Password must be at least 6 characters.",
    "error_credentials" to "Incorrect email or password.",
    "error_email_used" to "This email is already registered.",
    "error_network" to "No internet connection.",
    "error_too_many" to "Too many attempts. Try again later.",
    "error_auth" to "Couldn't sign in.",
    "reset_sent" to "Follow the link sent to your email.",
    "start_first" to "Start by logging your first visit",
    "empty_visits_title" to "No visits yet",
    "empty_visits_desc" to "Tap + to start your log.",
    "report_title" to "Weekly report",
    "this_week" to "This week",
    "last_week" to "Last week",
    "stat_visits" to "Visits",
    "stat_clients" to "Clients",
    "stat_success" to "Successful",
    "by_type" to "By visit type",
    "week_details" to "This week's details",
    "empty_week" to "No visits this week",
    "copy" to "Copy",
    "share" to "Share",
    "share_report" to "Share report",
    "export_excel" to "Export Excel",
    "report_lang" to "Report language",
    "report_lang_desc" to "The language used for the report and the Excel file",
    "reminder_time" to "Reminder time",
    "daily_goal" to "Daily goal",
    "set_goal_hint" to "Set your daily visit goal",
    "daily_goal_desc" to "How many visits you aim to make each day.",
    "clear_goal" to "Clear goal",
    "templates" to "Templates",
    "add_template_hint" to "Write a new template...",
    "calendar" to "Calendar",
    "change_photo" to "Change photo",
    "team" to "Team",
    "team_intro" to "Create a company as a manager, or join a team with an invite code.",
    "create_company" to "Create company",
    "company_name_hint" to "Company name",
    "join_company" to "Join with code",
    "invite_code_hint" to "Invite code",
    "invalid_code" to "That invite code is invalid.",
    "team_error" to "Something went wrong, try again.",
    "last_manager" to "A team needs at least one manager — promote another manager first.",
    "role_manager" to "Manager",
    "role_rep" to "Sales rep",
    "invite_code" to "Invite code",
    "team_members" to "Team members",
    "team_pipeline" to "Team pipeline",
    "team_share_opp" to "Share deal",
    "team_customers" to "Team customers",
    "team_customers_empty" to "No shared customers yet.",
    "team_customers_hint" to "Share a customer from that customer's page (the \"Share to team\" button).",
    "share_to_team" to "Share to team",
    "share_to_team_desc" to "Let every company member see this customer.",
    "shared_with_team" to "Shared with the team ✓",
    "share" to "Share",
    "unshare" to "Unshare",
    "team_pipeline_empty" to "No shared deals yet.",
    "owner" to "Owner",
    "attachments" to "Attachments",
    "add_file" to "Add file",
    "no_attachments" to "No attachments yet.",
    "att_local" to "On device (not uploaded yet)",
    "att_uploaded" to "Uploaded to Drive ✓",
    "drive_sync" to "Google sync (attachments + calendar)",
    "drive_sync_desc" to "Connect Google to sync attachments across devices and put tasks on your calendar — free.",
    "cal_synced" to "Added to Google Calendar (stays in sync)",
    "drive_connect" to "Connect",
    "drive_disconnect" to "Disconnect",
    "drive_connected" to "Google Drive connected",
    "drive_connected_as" to "Connected as",
    "you" to "You",
    "make_rep" to "Make rep",
    "make_manager" to "Make manager",
    "leave_company" to "Leave company",
    "work_distribution" to "Work distribution",
    "assign_work" to "Assign work",
    "no_assignments" to "No work assigned yet.",
    "assign_to" to "Assign to",
    "note" to "Note",
    "opportunities" to "Opportunities",
    "empty_opps_title" to "No opportunities yet",
    "empty_opps_desc" to "Add deals and track their stages.",
    "opps_total" to "Deals",
    "open_value" to "Open value",
    "stage_won" to "Won",
    "stage_lost" to "Lost",
    "stage_postponed" to "Postponed",
    "opp_active" to "Active",
    "opp_view_toggle" to "Board / list view",
    "new_opp" to "New opportunity",
    "edit_opp" to "Edit opportunity",
    "opp_title" to "Opportunity title",
    "opp_title_hint" to "e.g. Printers deal for Acme Co.",
    "opp_value" to "Value",
    "opp_product" to "Product / solution",
    "opp_product_hint" to "What we'll offer the customer",
    "opp_need" to "Customer need",
    "opp_need_hint" to "What exactly they need",
    "opp_problem" to "Problem & impact",
    "opp_problem_hint" to "The problem they face and its impact",
    "opp_budget" to "Budget",
    "opp_budget_amount" to "Budget amount",
    "opp_close_date" to "Expected purchase date",
    "opp_competitor" to "Competitor",
    "opp_competitor_hint" to "Who the competitor is, if known",
    "opp_blocker" to "Current blocker",
    "opp_blocker_hint" to "What's holding the deal up",
    "opp_decision_people" to "Decision people on this deal",
    "decision_maker" to "Decision maker",
    "opp_missing_prefix" to "Before a quote, still missing:",
    "opp_needs_next" to "An active deal should have a dated next step.",
    "opp_loss_reason" to "Loss reason",
    "opp_loss_reason_hint" to "Why the deal was lost",
    "loss_declared" to "Customer stated it",
    "loss_inferred" to "My inference",
    "opp_history" to "Stage history",
    "quotes" to "Quotes",
    "quote" to "Quote",
    "new_quote" to "New quote",
    "no_quotes" to "No quotes yet",
    "quote_status" to "Status",
    "quote_tax" to "Tax %",
    "quote_expiry" to "Expiry date",
    "quote_lines" to "Line items",
    "quote_line_desc" to "Description / product",
    "quote_qty" to "Qty",
    "quote_unit_price" to "Unit price",
    "quote_discount" to "Disc %",
    "quote_unit_cost" to "Cost",
    "quote_cost" to "Total cost",
    "quote_profit" to "Profit",
    "quote_export_pdf" to "Export PDF",
    "quote_pdf_failed" to "Couldn't create the file",
    "quote_line_net" to "Net",
    "quote_add_line" to "+ Line",
    "quote_add_stock" to "+ From stock",
    "quote_subtotal" to "Subtotal",
    "quote_total" to "Total",
    "quote_revision_note" to "Editing a sent quote's items saves a new revision; the original stays as the customer received it.",
    "quote_order_created" to "An order was created from this quote ✓",
    "quote_make_order" to "Create order from quote",
    "quote_pick_product" to "Pick a product",
    "dashboard" to "Manager dashboard",
    "team_goal" to "Team goal",
    "team_goal_desc" to "Number of assignments the team should complete.",
    "set_goal" to "Set goal",
    "assigned_total" to "Assigned",
    "by_rep" to "By rep",
    "note_ar" to "Arabic",
    "note_en" to "English",
    "tasks_added_prefix" to "Assistant added tasks:",
    "tools" to "Tools",
    "inventory" to "Stock",
    "prices" to "Prices",
    "ai_send" to "Send to assistant",
    "select" to "Select",
    "select_all" to "Select all",
    "search_items" to "Search items...",
    "import_excel" to "Import Excel",
    "import_hint" to "Excel/CSV with columns: name, quantity, price, currency.",
    "imported_prefix" to "Imported items:",
    "import_empty" to "No items found in the file.",
    "import_failed" to "Couldn't read the file. Make sure it's Excel or CSV.",
    "edit" to "Edit",
    "orders" to "Orders",
    "purchases" to "Purchases",
    "total_purchased" to "Total purchased",
    "add_order" to "Add order",
    "no_orders" to "No orders yet.",
    "order" to "Order",
    "order_ordered" to "In progress",
    "order_delivered" to "Delivered",
    "new_order" to "New order",
    "edit_order" to "Edit order",
    "order_items" to "Items / description",
    "order_items_hint" to "e.g. 3 × Atex 1500 printers",
    "order_amount" to "Amount",
    "order_status" to "Status",
    "order_date" to "Date",
    "mail" to "Mail",
    "mail_desc" to "Compose an email, pick the recipient from your customer contacts, and send it from your mail app.",
    "mail_to" to "To",
    "mail_to_hint" to "Recipient email",
    "mail_subject" to "Subject",
    "mail_subject_hint" to "Message subject",
    "mail_body" to "Message",
    "mail_body_hint" to "Write your message...",
    "mail_send" to "Send",
    "mail_pick" to "Pick from customers",
    "no_mail_app" to "No email app on this device.",
    "mail_hint_note" to "Opens your email app with the message ready — you review and send it yourself.",
    "no_contact_emails" to "No emails saved in your customer contacts.",
    "inventory_desc" to "Stock and prices the assistant checks to suggest your next step.",
    "stock_prices" to "Stock & prices",
    "empty_inventory_title" to "No items yet",
    "empty_inventory_desc" to "Add your items with quantities and prices.",
    "no_price" to "No price set",
    "in_stock" to "In stock",
    "out_of_stock" to "Out of stock",
    "new_item" to "New item",
    "edit_item" to "Edit item",
    "item_name" to "Item name",
    "item_name_hint" to "e.g. Atex 1500 printer",
    "quantity" to "Quantity",
    "price" to "Price",
    "currency" to "Currency",
    "currency_hint" to "e.g. SAR",
    "default_currency" to "Default currency",
    "default_currency_desc" to "The currency shown with prices and values.",
    "custom_currency" to "Other currency",
    "insights_sub" to "Overview of all your visits",
    "total" to "Total",
    "by_outcome" to "By outcome",
    "visits_by_month" to "Visits · last 6 months",
    "top_clients" to "Most-visited clients",
    "upcoming" to "Upcoming follow-ups",
    "empty_insights" to "Insights appear after your first visit",
    "client_name_hint" to "Client / company name",
    "notes_hint" to "Write the visit notes, what you discussed, and any important details...",
    "checklist" to "Checklist",
    "checklist_hint" to "New item...",
    "add_image" to "Add image",
    "customer_info" to "Customer info",
    "more" to "More",
    "delete_visit" to "Delete visit",
    "done" to "Done",
    "contact_person" to "Contact person",
    "contact_hint" to "Person's name (optional)",
    "industry" to "Industry",
    "industry_hint" to "e.g. retail, manufacturing, services...",
    "all" to "All",
    "relationship" to "Relationship",
    "city" to "City",
    "city_hint" to "e.g. Riyadh",
    "region" to "Region",
    "region_hint" to "e.g. Central Region",
    "website" to "Website",
    "website_hint" to "www...",
    "source" to "Source",
    "source_hint" to "e.g. referral, event, cold call, website...",
    "equipment" to "Current equipment",
    "equipment_hint" to "Machines/equipment they have now",
    "apps_field" to "Applications / work",
    "apps_hint" to "The kind of work or apps they run",
    "job_title_hint" to "Job title (e.g. Production Manager)",
    "decision_role" to "Decision role",
    "contacts" to "Contacts",
    "add_contact" to "Add contact",
    "choose_contact" to "Who to call?",
    "choose_customer" to "Choose customer",
    "contact_email_hint" to "Email (optional)",
    "location_url" to "Location link",
    "location_url_hint" to "Google Maps link (optional)",
    "open_location" to "Open location",
    "phone" to "Phone number",
    "phone_hint" to "e.g. 01xxxxxxxxx",
    "call" to "Call",
    "address" to "Address",
    "address_hint" to "Client address (optional)",
    "time" to "Time",
    "visit_type" to "Visit type",
    "outcome" to "Outcome",
    "next_step" to "Next step",
    "next_hint" to "e.g. send a quote, follow up next week...",
    "follow_date" to "Follow-up date",
    "none" to "None",
    "appearance" to "Appearance",
    "set_appearance" to "Appearance",
    "set_preferences" to "Preferences",
    "set_account" to "Account & sync",
    "set_ai" to "AI assistant",
    "set_data" to "Data & backup",
    "set_updates" to "Updates & info",
    "tools_sec_pipeline" to "Pipeline & sales",
    "tools_sec_insights" to "Insights & reports",
    "tools_sec_catalog" to "Products & catalog",
    "tools_sec_team" to "Team & communication",
    "theme_auto" to "Auto",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "color_style" to "Color style",
    "week_start" to "Week starts on",
    "day_sat" to "Saturday", "day_sun" to "Sunday", "day_mon" to "Monday", "day_tue" to "Tuesday",
    "day_wed" to "Wednesday", "day_thu" to "Thursday", "day_fri" to "Friday",
    "palette_classic" to "Classic",
    "palette_warm" to "Warm green",
    "language" to "Language",
    "lang_ar" to "العربية",
    "lang_en" to "English",
    "lang_auto" to "Auto",
    "delete_all" to "Delete all visits",
    "about" to "About",
    "version" to "Version",
    "delete_all_q" to "Delete all visits?",
    "delete_all_desc" to "This permanently deletes all recorded visits.",
    "delete" to "Delete",
    "cancel" to "Cancel",
    "client_required" to "Enter the client name first.",
    "discard" to "Discard",
    "keep_editing" to "Keep editing",
    "discard_q" to "Leave without saving?",
    "discard_desc" to "The visit result or next step is still missing. If you leave now your changes won't be saved.",
    "discard_no_client" to "The client name is missing. If you leave now your changes won't be saved.",
    "today" to "Today",
    "today_title" to "Today's route",
    "today_sub" to "Clients you plan to visit today",
    "add_client_hint" to "Client name...",
    "plan_hint" to "Type the task, @ to pick a client",
    "add" to "Add",
    "seg_all" to "All",
    "seg_todo" to "To do",
    "seg_done" to "Done",
    "seg_none_todo" to "No stops left 🎉",
    "seg_none_done" to "No stops completed yet",
    "tasks_tab" to "Tasks",
    "save" to "Save",
    "of" to "of",
    "hrs" to "hrs",
    "duration" to "Duration",
    "morning" to "Morning",
    "afternoon" to "Afternoon",
    "evening" to "Evening",
    "new_task" to "New task",
    "edit_task" to "Edit task",
    "task_action" to "Task",
    "task_status" to "Status",
    "task_details" to "Task details",
    "task_source" to "Source",
    "date" to "Date",
    "result" to "Result",
    "mark_done" to "Mark done",
    "mark_undone" to "Reopen",
    "add_to_calendar" to "Add to calendar",
    "empty_tasks_title" to "No tasks for today",
    "empty_tasks_desc" to "Add your tasks and track your progress.",
    "reschedule" to "Move to another day",
    "move_tomorrow" to "Move to tomorrow",
    "move_day_after" to "Move to day after",
    "move_pick_day" to "Pick a day",
    "empty_today_title" to "No stops for today",
    "empty_today_desc" to "Add the clients you'll visit and build your route.",
    "stops_done" to "stops done",
    "today_progress" to "Today's progress",
    "day_progress" to "Day's progress",
    "empty_day_title" to "No stops for this day",
    "completed" to "Completed",
    "remaining" to "Remaining",
    "followups_short" to "Follow-ups",
    "today_plan" to "Visit plan",
    "quick_result" to "Quick result",
    "quick_next" to "Next step",
    "template_quote" to "Send a quote",
    "template_call" to "Call the customer",
    "template_follow" to "Schedule follow-up",
    "open_route" to "Open route in Maps",
    "navigate" to "Directions",
    "route_limit" to "Only the first 10 stops were sent to Maps",
    "updates" to "Updates",
    "check_update" to "Check for updates",
    "checking" to "Checking...",
    "up_to_date" to "You're on the latest version",
    "update_available" to "Update available",
    "downloading" to "Downloading",
    "install_update" to "Install update",
    "update_failed" to "Couldn't check",
    "customers" to "Customers",
    "add_customer" to "Add customer",
    "search_customers" to "Search by name or phone...",
    "search_visits" to "Search visits and notes...",
    "empty_customers" to "No customers yet",
    "empty_customers_desc" to "Add your first customer, or log a visit and they will appear automatically.",
    "no_results" to "No matching results",
    "visit_count" to "visits",
    "no_visits" to "No visits yet",
    "new_customer" to "New customer",
    "customer_details" to "Customer details",
    "customer_name" to "Customer / company name",
    "customer_notes" to "Customer notes",
    "customer_notes_hint" to "Any useful long-term details about this customer...",
    "visit_history" to "Visit history",
    "timeline" to "Timeline",
    "visit" to "Visit",
    "log_activity" to "Log activity",
    "edit_activity" to "Edit activity",
    "no_activity" to "No activity yet",
    "activity_type" to "Activity type",
    "activity_result" to "Result",
    "activity_date" to "Date",
    "activity_summary" to "Summary",
    "activity_summary_hint" to "What happened on the call/meeting...",
    "opp_link" to "Link to a deal",
    "delete_customer" to "Delete customer",
    "delete_customer_q" to "Delete customer?",
    "delete_customer_desc" to "Only the customer card will be removed. Their visits will remain saved.",
    "reminders" to "Reminders",
    "enable_reminders" to "Enable follow-up reminders",
    "enable_reminders_desc" to "We'll remind you when a customer follow-up is due.",
    "due_followups" to "Due and overdue follow-ups",
    "agenda_overdue" to "Overdue",
    "agenda_today" to "Due today",
    "agenda_suggestions" to "Needs a decision",
    "reason_appointment" to "Appointment",
    "reason_due_today" to "Today",
    "reason_needs_action" to "Deal with no next step",
    "reason_expired" to "Quote expired",
    "postpone" to "Postpone",
    "smart_automation" to "Smart automations",
    "smart_automation_desc" to "Quote sent → auto follow-up and advance the deal stage; deal closed → cancel its upcoming follow-ups.",
    "agree" to "Agree",
    "retry" to "Retry",
    "previsit_prep" to "Prepare me for the visit",
    "previsit_pick_opp" to "Choose the opportunity",
    "previsit_general" to "General brief (all deals)",
    "previsit_thinking" to "Preparing the brief from your data...",
    "previsit_summary" to "Summary",
    "previsit_goal" to "Suggested visit goal",
    "previsit_questions" to "Key questions to ask",
    "previsit_commitments" to "Past commitments",
    "previsit_watch" to "Things to verify",
    "previsit_disclaimer" to "Based only on what's recorded in the app; review before relying on it.",
    "ai_consent_title" to "Use the AI assistant",
    "ai_consent_desc" to "Selected data for this customer (summary, recent interactions, deals, quotes) will be sent to the AI provider (Gemini) using your key to prepare the brief. No keys are sent, and you can turn this off in Settings.",
    "compose_ai" to "Write message (AI)",
    "compose_type" to "Message type",
    "compose_tone" to "Tone",
    "compose_recipient" to "Recipient",
    "compose_generate" to "Generate draft",
    "compose_regenerate" to "Regenerate",
    "compose_subject" to "Subject",
    "compose_body" to "Body",
    "extract_details" to "Extract details (AI)",
    "extract_need_note" to "Write or record a note first.",
    "extract_title" to "Details extracted from the visit",
    "extract_apply_to" to "Applies to",
    "extract_new_deal" to "No deal — a new one will be created for this customer.",
    "extract_nothing" to "No clear details to extract.",
    "extract_objection" to "Objection",
    "extract_suggestion_note" to "These are suggestions needing your confirmation — uncheck anything you don't want applied.",
    "extract_current" to "Current",
    "extract_proposed" to "Proposed",
    "extract_apply" to "Apply selected",
    "assistant" to "Assistant",
    "assistant_hint" to "Type a command in your own words — I turn it into an action you confirm before it runs.",
    "assistant_placeholder" to "e.g. Add a follow-up for Ahmed Thursday 10am",
    "cmd_add_task" to "Add follow-up",
    "cmd_customer_unmatched" to "Customer not matched exactly — it'll be added by name as-is.",
    "cmd_confirm" to "Confirm",
    "cmd_dup" to "A matching follow-up already exists.",
    "cmd_added" to "Added ✓",
    "cmd_reschedule" to "Move follow-up",
    "cmd_task_not_found" to "No matching follow-up found.",
    "cmd_moved" to "Moved ✓",
    "cmd_unknown" to "I didn't understand — try rephrasing.",
    "ask_data" to "Ask your data",
    "ask_coach" to "Sales coach",
    "ask_on_track" to "Everything looks on track 👍",
    "ask_summarize" to "Summarize with AI",
    "ask_scope_note" to "All numbers are computed locally from your data (overdue is counted up to today).",
    "q_overdue" to "Overdue follow-ups",
    "q_quotes_nofu" to "Sent quotes with no logged follow-up",
    "q_opps_nodm" to "Active deals with no decision maker",
    "q_opps_nonext" to "Active deals with no next step",
    "q_prospects" to "Prospects",
    "analytics" to "Analytics",
    "period_week" to "Week",
    "period_month" to "Month",
    "period_30" to "Last 30 days",
    "m_new_prospects" to "New prospects",
    "m_interactions" to "Completed interactions",
    "m_no_answer" to "Calls with no answer",
    "m_quotes_sent" to "Quotes sent",
    "m_won" to "Deals won",
    "m_lost" to "Deals lost",
    "m_adherence" to "Follow-up adherence",
    "m_pipeline" to "Active pipeline value",
    "m_pipeline_note" to "Current snapshot, not period-bound.",
    "m_won_value" to "Won value in period",
    "m_sales" to "Actual sales (orders) in period",
    "m_sales_note" to "Real orders — separate from pipeline.",
    "analytics_note" to "All numbers computed locally. Comparison is vs the previous same-length period. Currencies are kept separate, never summed.",
    "weekly_review" to "Weekly review",
    "generated" to "Generated",
    "wr_happened" to "What happened",
    "wr_attention" to "Needs attention",
    "wr_focus" to "Focus for next week",
    "wr_add_focus" to "Add as a task today",
    "wr_ai_summary" to "AI summary (optional)",
    "wr_fact_note" to "The numbers are facts computed locally; the AI summary is a reading aid, not a source of numbers.",
    "focus_overdue" to "Clear overdue follow-ups first — they stall deals the most.",
    "focus_quotes" to "Follow up on sent quotes that have no logged reply yet.",
    "focus_nextstep" to "Set a dated next step for every active deal.",
    "focus_dm" to "Identify the decision maker on deals that still lack one.",
    "focus_ok" to "You're on track — keep the rhythm. 👍",
    "dev_goal" to "This week's development goal",
    "dev_last_goal" to "Last week's goal",
    "dev_goal_hint" to "One behavior to work on (e.g. document the decision-maker on every deal)",
    "dev_save_goal" to "Save goal",
    "dev_goal_note" to "A measurable behavior, reviewed next week — no score out of 100.",
    "lost_deals" to "Lost deals",
    "lost_patterns" to "Recurring patterns",
    "lost_pattern_note" to "A pattern shows only when it repeats (2+) — never from a single case.",
    "lost_none" to "No lost deals recorded.",
    "lost_last_stage" to "Last stage",
    "lost_duration" to "Deal duration",
    "lost_reason" to "Loss reason",
    "days" to "days",
    "lost_reflect" to "Reflection questions",
    "lost_q1" to "What was the first warning sign?",
    "lost_q2" to "What did we know but not act on?",
    "lost_q3" to "What behavior will we try changing next time?",
    "product_knowledge" to "Products & knowledge",
    "objections" to "Objection library",
    "projects" to "Projects & account map",
    "proj_none" to "No projects yet. Add a big project and group its deals.",
    "proj_deals" to "deals",
    "proj_stakeholders" to "stakeholders",
    "proj_add" to "New project",
    "proj_edit" to "Edit project",
    "proj_name" to "Project name",
    "proj_desc" to "Description",
    "proj_status" to "Status",
    "proj_target" to "Expected decision date",
    "proj_link_deals" to "Linked deals",
    "proj_no_deals" to "No deals for this customer yet — add one first to link it.",
    "proj_total" to "Total project value",
    "account_map" to "Account map (decision makers)",
    "needs_linking" to "Needs linking",
    "needs_linking_desc" to "Records with a customer name not tied to a stable customer — pick the right customer to link them all.",
    "needs_linking_none" to "All records are linked ✓",
    "needs_linking_records" to "records",
    "needs_linking_link" to "Link",
    "pk_search" to "Search by need (e.g. printing on fabric)",
    "pk_no_match" to "No product matches that need.",
    "pk_match_why" to "Matched on",
    "pk_none" to "No product knowledge yet. Add one with +",
    "pk_verified" to "Verified",
    "pk_needs_check" to "Needs check",
    "pk_add" to "New product",
    "pk_edit" to "Edit product",
    "pk_name" to "Product name",
    "pk_manufacturer" to "Manufacturer",
    "pk_model" to "Model",
    "pk_specs" to "Specifications",
    "pk_applications" to "Applications / uses",
    "pk_materials" to "Supported materials",
    "pk_limits" to "Limitations",
    "pk_suitable" to "Suitable for",
    "pk_source" to "Source",
    "pk_verified_toggle" to "Information verified",
    "obj_none" to "No objections recorded. Add one with +",
    "obj_add" to "New objection",
    "obj_edit" to "Edit objection",
    "obj_text" to "Objection",
    "obj_probe" to "Discovery question",
    "obj_evidence" to "Evidence / use case",
    "obj_response" to "Suggested response",
    "overdue" to "Overdue",
    "backup" to "Backup",
    "backup_desc" to "Keep a copy of your customers and visits on this device.",
    "export_backup" to "Save a backup",
    "import_backup" to "Restore a backup",
    "backup_saved" to "Backup saved",
    "backup_restored" to "Data restored",
    "backup_failed" to "Couldn't read this backup file",
    "ai_formatting" to "AI note formatting",
    "ai_desc" to "Write or dictate your visit notes casually, and the app formats them professionally in Arabic and English. Needs a free Gemini key.",
    "api_key" to "Gemini API key",
    "api_key_hint" to "Paste your key here",
    "get_key" to "Get a free key from Google AI Studio",
    "ai_test" to "Test key",
    "ai_testing" to "Testing...",
    "ai_test_ok" to "Key works ✓",
    "ai_saved" to "Key saved",
    "polish" to "Format with AI",
    "polishing" to "Formatting...",
    "purpose" to "Purpose of visit",
    "purpose_desc" to "Choose the visit purpose (required).",
    "need_key" to "Add a Gemini key in Settings first",
    "ai_result" to "Formatted version",
    "notes_ar_label" to "Arabic",
    "notes_en_label" to "English",
    "voice_input" to "Voice recording",
    "mic_denied" to "Microphone permission is needed to record",
    "rec_failed" to "Recording too short or failed — try again",
    "copied" to "Copied",
    "ai_failed" to "Couldn't format",
    "voice_assistant" to "Voice assistant",
    "voice_assistant_desc" to "Talk and ask about your day and your data.",
    "voice_you_said" to "You said:",
    "voice_listening" to "Listening…",
    "voice_thinking" to "Thinking…",
    "voice_speaking" to "Answering…",
    "voice_tap_to_talk" to "Tap and talk",
    "voice_replay" to "Replay",
    "voice_examples" to "e.g. \"How many visits do I have today?\" · \"Who's overdue on follow-ups?\"",
    "voice_didnt_catch" to "Didn't catch that, try again.",
    "voice_unavailable" to "Speech recognition isn't available on this device.",
    "voice_need_mic" to "I need microphone permission to hear you.",
)

val AR = L(false, AR_MAP)
val EN = L(true, EN_MAP)

val LocalL = staticCompositionLocalOf { AR }

/** Subtitle: "5 زيارة مسجّلة · 4 هذا الأسبوع" / "5 visits · 4 this week" */
fun visitsSubtitle(total: Int, week: Int, en: Boolean): String =
    if (en) "$total visits · $week this week" else "$total زيارة مسجّلة · $week هذا الأسبوع"
